# Generated by Django 4.1.4 on 2022-12-10 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='customer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='customer', to='api.tg_user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manager', to='api.tg_user'),
        ),
    ]
