# Generated by Django 4.1.4 on 2022-12-10 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_conversation_customer_alter_project_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=60)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.tg_user')),
            ],
        ),
    ]
