# Generated by Django 4.1.4 on 2022-12-10 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.project')),
            ],
        ),
    ]
