# Generated by Django 4.1.4 on 2022-12-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=60)),
                ('created', models.DateTimeField(auto_now=True)),
                ('cheaker', models.BooleanField(default=False)),
                ('from_who', models.CharField(max_length=60)),
            ],
        ),
    ]
