# Generated by Django 4.1.4 on 2022-12-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='cheaker',
        ),
        migrations.AddField(
            model_name='event',
            name='cheaked',
            field=models.BooleanField(default=False),
        ),
    ]
